aiera.ai.vector.db.connectError=Failed to connect to ${0} vector database.